version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      support-dependencies:
        patterns:
          - "*"
