---
# See https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md.
default: true
heading-style:
  style: atx
ul-style:
  style: dash
line-length: false
no-duplicate-heading:
  siblings_only: true
no-inline-html: false
