import 'package:flutter/widgets.dart';
import 'package:flutter_gen/gen_l10n/locations_localizations.dart';

extension LocalizedBuildContext on BuildContext {
  LocationsLocalizations get locationsLoc => LocationsLocalizations.of(this);
}

extension LocationsLocalizationsGetter on LocationsLocalizations {
  String? getLocation(String key) {
    switch (key) {
      case 'location_Abdon':
        return location_Abdon;
      case 'location_Abel_beth_maacah':
        return location_Abel_beth_maacah;
      case 'location_Abel_keramim':
        return location_Abel_keramim;
      case 'location_Abel_meholah':
        return location_Abel_meholah;
      case 'location_Abila':
        return location_Abila;
      case 'location_Abilene':
        return location_Abilene;
      case 'location_Abronah':
        return location_Abronah;
      case 'location_Acco':
        return location_Acco;
      case 'location_Achaia':
        return location_Achaia;
      case 'location_Achmetha_Ecbatana':
        return location_Achmetha_Ecbatana;
      case 'location_Achzib':
        return location_Achzib;
      case 'location_Actium':
        return location_Actium;
      case 'location_Adam':
        return location_Adam;
      case 'location_Addar_Hazar_addar':
        return location_Addar_Hazar_addar;
      case 'location_Adullam':
        return location_Adullam;
      case 'location_Aenon':
        return location_Aenon;
      case 'location_Ai':
        return location_Ai;
      case 'location_Aijalon':
        return location_Aijalon;
      case 'location_Ain_Simeon':
        return location_Ain_Simeon;
      case 'location_Ain_Ashan_Simeon_Levi':
        return location_Ain_Ashan_Simeon_Levi;
      case 'location_Akrabbim':
        return location_Akrabbim;
      case 'location_Aleppo':
        return location_Aleppo;
      case 'location_Alexandria_Carmania':
        return location_Alexandria_Carmania;
      case 'location_Alexandria_Egypt':
        return location_Alexandria_Egypt;
      case 'location_Alexandria_India':
        return location_Alexandria_India;
      case 'location_Alexandria_Arachosiorum':
        return location_Alexandria_Arachosiorum;
      case 'location_Alexandria_Areion':
        return location_Alexandria_Areion;
      case 'location_Alexandria_Eschate':
        return location_Alexandria_Eschate;
      case 'location_Alexandria_Margiana':
        return location_Alexandria_Margiana;
      case 'location_Alexandria_Oxiana':
        return location_Alexandria_Oxiana;
      case 'location_Alexandria_Prophthasia':
        return location_Alexandria_Prophthasia;
      case 'location_Almon':
        return location_Almon;
      case 'location_Almon_diblathaim':
        return location_Almon_diblathaim;
      case 'location_Amalekites':
        return location_Amalekites;
      case 'location_Ammon':
        return location_Ammon;
      case 'location_Amorites':
        return location_Amorites;
      case 'location_Amphipolis':
        return location_Amphipolis;
      case 'location_Anab':
        return location_Anab;
      case 'location_Anathoth':
        return location_Anathoth;
      case 'location_Ankara':
        return location_Ankara;
      case 'location_Antioch_Pisidia':
        return location_Antioch_Pisidia;
      case 'location_Antioch_Syria':
        return location_Antioch_Syria;
      case 'location_Antipatris_Aphek':
        return location_Antipatris_Aphek;
      case 'location_Aphek_Asher':
        return location_Aphek_Asher;
      case 'location_Aphek_Manasseh':
        return location_Aphek_Manasseh;
      case 'location_Aphek_Antipatris_Ephraim':
        return location_Aphek_Antipatris_Ephraim;
      case 'location_Arabah':
        return location_Arabah;
      case 'location_Arabia':
        return location_Arabia;
      case 'location_Arabian_Desert':
        return location_Arabian_Desert;
      case 'location_Arachosia':
        return location_Arachosia;
      case 'location_Arad_Canaanite':
        return location_Arad_Canaanite;
      case 'location_Arad_Israelite':
        return location_Arad_Israelite;
      case 'location_Ararat':
        return location_Ararat;
      case 'location_Arbel':
        return location_Arbel;
      case 'location_Aria':
        return location_Aria;
      case 'location_Arimathea_Ramah':
        return location_Arimathea_Ramah;
      case 'location_Armenia':
        return location_Armenia;
      case 'location_Arnon':
        return location_Arnon;
      case 'location_Aroer':
        return location_Aroer;
      case 'location_Arpad':
        return location_Arpad;
      case 'location_Arubboth':
        return location_Arubboth;
      case 'location_Arumah':
        return location_Arumah;
      case 'location_Ashan_Ain':
        return location_Ashan_Ain;
      case 'location_Ashdod':
        return location_Ashdod;
      case 'location_Asher':
        return location_Asher;
      case 'location_Asher_tribe':
        return location_Asher_tribe;
      case 'location_Ashkelon':
        return location_Ashkelon;
      case 'location_Ashtaroth_Beeshterah':
        return location_Ashtaroth_Beeshterah;
      case 'location_Asia_Roman':
        return location_Asia_Roman;
      case 'location_Asia_Minor':
        return location_Asia_Minor;
      case 'location_Asshur':
        return location_Asshur;
      case 'location_Assos':
        return location_Assos;
      case 'location_Assyria':
        return location_Assyria;
      case 'location_Ataroth':
        return location_Ataroth;
      case 'location_Athens':
        return location_Athens;
      case 'location_Attalia':
        return location_Attalia;
      case 'location_Azekah':
        return location_Azekah;
      case 'location_Azmaveth':
        return location_Azmaveth;
      case 'location_Azmon':
        return location_Azmon;
      case 'location_Baal_Ramah':
        return location_Baal_Ramah;
      case 'location_Baalath_beer_Ramah':
        return location_Baalath_beer_Ramah;
      case 'location_Baal_gad':
        return location_Baal_gad;
      case 'location_Baal_hazor':
        return location_Baal_hazor;
      case 'location_Baal_meon':
        return location_Baal_meon;
      case 'location_Baal_perazim':
        return location_Baal_perazim;
      case 'location_Baal_shalishah':
        return location_Baal_shalishah;
      case 'location_Babylonia':
        return location_Babylonia;
      case 'location_Bactra':
        return location_Bactra;
      case 'location_Bactria':
        return location_Bactria;
      case 'location_Bahurim':
        return location_Bahurim;
      case 'location_Bamoth_baal':
        return location_Bamoth_baal;
      case 'location_Bashan':
        return location_Bashan;
      case 'location_Beer_lahai_roi':
        return location_Beer_lahai_roi;
      case 'location_Beer_sheba':
        return location_Beer_sheba;
      case 'location_Beeshterah_Ashtaroth':
        return location_Beeshterah_Ashtaroth;
      case 'location_Bene_jaakan':
        return location_Bene_jaakan;
      case 'location_Benjamin':
        return location_Benjamin;
      case 'location_Beroea':
        return location_Beroea;
      case 'location_Berothai_Cun':
        return location_Berothai_Cun;
      case 'location_Besor':
        return location_Besor;
      case 'location_Beth_anath':
        return location_Beth_anath;
      case 'location_Bethany':
        return location_Bethany;
      case 'location_Bethany_across_the_Jordan':
        return location_Bethany_across_the_Jordan;
      case 'location_Beth_arabah':
        return location_Beth_arabah;
      case 'location_Beth_biri_Beth_lebaoth':
        return location_Beth_biri_Beth_lebaoth;
      case 'location_Beth_dagon':
        return location_Beth_dagon;
      case 'location_Bethel_Luz':
        return location_Bethel_Luz;
      case 'location_Beth_emek':
        return location_Beth_emek;
      case 'location_Beth_ezel':
        return location_Beth_ezel;
      case 'location_Beth_haran':
        return location_Beth_haran;
      case 'location_Beth_hoglah':
        return location_Beth_hoglah;
      case 'location_Beth_horon':
        return location_Beth_horon;
      case 'location_Beth_jeshimoth':
        return location_Beth_jeshimoth;
      case 'location_Beth_lebaoth_Beth_biri':
        return location_Beth_lebaoth_Beth_biri;
      case 'location_Bethlehem_Zebulun':
        return location_Bethlehem_Zebulun;
      case 'location_Bethlehem_Ephrath_Judah':
        return location_Bethlehem_Ephrath_Judah;
      case 'location_Beth_marcaboth_Madmannah':
        return location_Beth_marcaboth_Madmannah;
      case 'location_Beth_nimrah':
        return location_Beth_nimrah;
      case 'location_Beth_peor':
        return location_Beth_peor;
      case 'location_Bethphage':
        return location_Bethphage;
      case 'location_Bethsaida':
        return location_Bethsaida;
      case 'location_Beth_shean_Beth_shan_Scythopolis':
        return location_Beth_shean_Beth_shan_Scythopolis;
      case 'location_Beth_shemesh_Issachar':
        return location_Beth_shemesh_Issachar;
      case 'location_Beth_shemesh_Judah':
        return location_Beth_shemesh_Judah;
      case 'location_Beth_shittah':
        return location_Beth_shittah;
      case 'location_Bethuel_Hazor':
        return location_Bethuel_Hazor;
      case 'location_Bethzatha':
        return location_Bethzatha;
      case 'location_Beth_zur':
        return location_Beth_zur;
      case 'location_Betonim':
        return location_Betonim;
      case 'location_Bezek':
        return location_Bezek;
      case 'location_Bezer':
        return location_Bezer;
      case 'location_Bithynia':
        return location_Bithynia;
      case 'location_Bozrah':
        return location_Bozrah;
      case 'location_Britain':
        return location_Britain;
      case 'location_Bukhara':
        return location_Bukhara;
      case 'location_Byzantium':
        return location_Byzantium;
      case 'location_Cabul':
        return location_Cabul;
      case 'location_Caesarea':
        return location_Caesarea;
      case 'location_Caesarea_Philippi':
        return location_Caesarea_Philippi;
      case 'location_Calah':
        return location_Calah;
      case 'location_Cana':
        return location_Cana;
      case 'location_Canaan':
        return location_Canaan;
      case 'location_Canatha':
        return location_Canatha;
      case 'location_Capernaum':
        return location_Capernaum;
      case 'location_Cappadocia':
        return location_Cappadocia;
      case 'location_Carchemish':
        return location_Carchemish;
      case 'location_Carmania':
        return location_Carmania;
      case 'location_Carmel':
        return location_Carmel;
      case 'location_Carmel_Judah':
        return location_Carmel_Judah;
      case 'location_Carthage':
        return location_Carthage;
      case 'location_Cauda':
        return location_Cauda;
      case 'location_Chaldea':
        return location_Chaldea;
      case 'location_Chephirah':
        return location_Chephirah;
      case 'location_Chesil_Hazor_Bethuel':
        return location_Chesil_Hazor_Bethuel;
      case 'location_Chesulloth':
        return location_Chesulloth;
      case 'location_Chinnereth':
        return location_Chinnereth;
      case 'location_Chios':
        return location_Chios;
      case 'location_Chitlish':
        return location_Chitlish;
      case 'location_Chorazin':
        return location_Chorazin;
      case 'location_Cilicia':
        return location_Cilicia;
      case 'location_Cnidus':
        return location_Cnidus;
      case 'location_Colossae':
        return location_Colossae;
      case 'location_Constantinople_Byzantium':
        return location_Constantinople_Byzantium;
      case 'location_Corinth':
        return location_Corinth;
      case 'location_Cos':
        return location_Cos;
      case 'location_Crete':
        return location_Crete;
      case 'location_Cun_Berothai':
        return location_Cun_Berothai;
      case 'location_Cyprus':
        return location_Cyprus;
      case 'location_Cyrene':
        return location_Cyrene;
      case 'location_Dabbesheth':
        return location_Dabbesheth;
      case 'location_Daberath':
        return location_Daberath;
      case 'location_Damascus':
        return location_Damascus;
      case 'location_Dan_tribe':
        return location_Dan_tribe;
      case 'location_Dan_Laish_city':
        return location_Dan_Laish_city;
      case 'location_Debir_Levi':
        return location_Debir_Levi;
      case 'location_Debir_Lo_debar_Gad':
        return location_Debir_Lo_debar_Gad;
      case 'location_Decapolis':
        return location_Decapolis;
      case 'location_Derbe':
        return location_Derbe;
      case 'location_Derbent':
        return location_Derbent;
      case 'location_Dibon_Dibon_gad':
        return location_Dibon_Dibon_gad;
      case 'location_Dimnah':
        return location_Dimnah;
      case 'location_Dimon':
        return location_Dimon;
      case 'location_Dion':
        return location_Dion;
      case 'location_Dophkah':
        return location_Dophkah;
      case 'location_Dor':
        return location_Dor;
      case 'location_Dothan':
        return location_Dothan;
      case 'location_Drangiana':
        return location_Drangiana;
      case 'location_Drapsaca':
        return location_Drapsaca;
      case 'location_Ebal':
        return location_Ebal;
      case 'location_Ebenezer':
        return location_Ebenezer;
      case 'location_Ecbatana_Achmetha':
        return location_Ecbatana_Achmetha;
      case 'location_Eden':
        return location_Eden;
      case 'location_Edom':
        return location_Edom;
      case 'location_Edrei_Manasseh':
        return location_Edrei_Manasseh;
      case 'location_Edrei_Naphtali':
        return location_Edrei_Naphtali;
      case 'location_Eglaim':
        return location_Eglaim;
      case 'location_Eglon':
        return location_Eglon;
      case 'location_Egypt':
        return location_Egypt;
      case 'location_Egypt__T_V_of':
        return location_Egypt__T_V_of;
      case 'location_Ekron':
        return location_Ekron;
      case 'location_Elam':
        return location_Elam;
      case 'location_Elath_Eloth':
        return location_Elath_Eloth;
      case 'location_Elburz':
        return location_Elburz;
      case 'location_Elealeh':
        return location_Elealeh;
      case 'location_Elim':
        return location_Elim;
      case 'location_Eloth_Elath':
        return location_Eloth_Elath;
      case 'location_Eltekeh':
        return location_Eltekeh;
      case 'location_Emmaus':
        return location_Emmaus;
      case 'location_En_dor':
        return location_En_dor;
      case 'location_En_gannim':
        return location_En_gannim;
      case 'location_En_gedi':
        return location_En_gedi;
      case 'location_En_rimmon_Ain_Simeon':
        return location_En_rimmon_Ain_Simeon;
      case 'location_En_rogel':
        return location_En_rogel;
      case 'location_En_shemesh':
        return location_En_shemesh;
      case 'location_Ephesus':
        return location_Ephesus;
      case 'location_Ephraim_tribe':
        return location_Ephraim_tribe;
      case 'location_Ephraim_Ophrah':
        return location_Ephraim_Ophrah;
      case 'location_Ephrath_Bethlehem_Judah':
        return location_Ephrath_Bethlehem_Judah;
      case 'location_Erech':
        return location_Erech;
      case 'location_Eshtaol':
        return location_Eshtaol;
      case 'location_Eshtemoa':
        return location_Eshtemoa;
      case 'location_Etam_Judah':
        return location_Etam_Judah;
      case 'location_Etam_Simeon':
        return location_Etam_Simeon;
      case 'location_Etham':
        return location_Etham;
      case 'location_Etham_campsite':
        return location_Etham_campsite;
      case 'location_Ether_Tochen':
        return location_Ether_Tochen;
      case 'location_Ethiopia':
        return location_Ethiopia;
      case 'location_Euphrates':
        return location_Euphrates;
      case 'location_Ezem':
        return location_Ezem;
      case 'location_Ezion_geber':
        return location_Ezion_geber;
      case 'location_Farah':
        return location_Farah;
      case 'location_Fertile_Crescent':
        return location_Fertile_Crescent;
      case 'location_Gad':
        return location_Gad;
      case 'location_Gadara':
        return location_Gadara;
      case 'location_Galatia':
        return location_Galatia;
      case 'location_Galilee':
        return location_Galilee;
      case 'location_Gallim':
        return location_Gallim;
      case 'location_Gamala':
        return location_Gamala;
      case 'location_Gath':
        return location_Gath;
      case 'location_Gath_hepher':
        return location_Gath_hepher;
      case 'location_Gath_rimmon_Dan':
        return location_Gath_rimmon_Dan;
      case 'location_Gath_rimmon_Ibleam_Manasseh':
        return location_Gath_rimmon_Ibleam_Manasseh;
      case 'location_Gaugamela':
        return location_Gaugamela;
      case 'location_Gaul':
        return location_Gaul;
      case 'location_Gaza':
        return location_Gaza;
      case 'location_Geba':
        return location_Geba;
      case 'location_Gederah':
        return location_Gederah;
      case 'location_Gedrosia':
        return location_Gedrosia;
      case 'location_Gehenna_Hinnom':
        return location_Gehenna_Hinnom;
      case 'location_Gerar':
        return location_Gerar;
      case 'location_Gerar_city':
        return location_Gerar_city;
      case 'location_Gerasa':
        return location_Gerasa;
      case 'location_Gerizim':
        return location_Gerizim;
      case 'location_Germania':
        return location_Germania;
      case 'location_Geshur':
        return location_Geshur;
      case 'location_Gethsemane':
        return location_Gethsemane;
      case 'location_Gezer':
        return location_Gezer;
      case 'location_Gibbethon':
        return location_Gibbethon;
      case 'location_Gibeah_Benjamin':
        return location_Gibeah_Benjamin;
      case 'location_Gibeah_Judah':
        return location_Gibeah_Judah;
      case 'location_Gibeon':
        return location_Gibeon;
      case 'location_Gihon':
        return location_Gihon;
      case 'location_Gilboa':
        return location_Gilboa;
      case 'location_Gilead':
        return location_Gilead;
      case 'location_Gilgal_by_Jordan':
        return location_Gilgal_by_Jordan;
      case 'location_Gilgal_Ephraim':
        return location_Gilgal_Ephraim;
      case 'location_Giloh':
        return location_Giloh;
      case 'location_Gimzo':
        return location_Gimzo;
      case 'location_Girgashites':
        return location_Girgashites;
      case 'location_Golan':
        return location_Golan;
      case 'location_Golgotha':
        return location_Golgotha;
      case 'location_Gordium':
        return location_Gordium;
      case 'location_Goshen_Egypt':
        return location_Goshen_Egypt;
      case 'location_Goshen_Judah':
        return location_Goshen_Judah;
      case 'location_Gozan':
        return location_Gozan;
      case 'location_Greece':
        return location_Greece;
      case 'location_Hadadrimmon':
        return location_Hadadrimmon;
      case 'location_Hadid':
        return location_Hadid;
      case 'location_Hali':
        return location_Hali;
      case 'location_Ham':
        return location_Ham;
      case 'location_Hamath':
        return location_Hamath;
      case 'location_Hammath_Hammoth_dor':
        return location_Hammath_Hammoth_dor;
      case 'location_Hammon':
        return location_Hammon;
      case 'location_Hammoth_dor_Hammath':
        return location_Hammoth_dor_Hammath;
      case 'location_Haran':
        return location_Haran;
      case 'location_Harod':
        return location_Harod;
      case 'location_Harosheth':
        return location_Harosheth;
      case 'location_Hazar_addar_Addar':
        return location_Hazar_addar_Addar;
      case 'location_Hazar_shual':
        return location_Hazar_shual;
      case 'location_Hazar_susah_Sansannah':
        return location_Hazar_susah_Sansannah;
      case 'location_Hazar_susim_Sansannah':
        return location_Hazar_susim_Sansannah;
      case 'location_Hazeroth':
        return location_Hazeroth;
      case 'location_Hazor_Benjamin':
        return location_Hazor_Benjamin;
      case 'location_Hazor_Naphtali':
        return location_Hazor_Naphtali;
      case 'location_Hazor_Bethuel':
        return location_Hazor_Bethuel;
      case 'location_Hebron_Kiriath_arba':
        return location_Hebron_Kiriath_arba;
      case 'location_Hecatompylos':
        return location_Hecatompylos;
      case 'location_Helam':
        return location_Helam;
      case 'location_Helbah':
        return location_Helbah;
      case 'location_Helkath':
        return location_Helkath;
      case 'location_Hepher':
        return location_Hepher;
      case 'location_Hermon':
        return location_Hermon;
      case 'location_Herodium':
        return location_Herodium;
      case 'location_Heshbon':
        return location_Heshbon;
      case 'location_Hinnom':
        return location_Hinnom;
      case 'location_Hippos':
        return location_Hippos;
      case 'location_Hittites':
        return location_Hittites;
      case 'location_Hivites':
        return location_Hivites;
      case 'location_Hobah':
        return location_Hobah;
      case 'location_Holon':
        return location_Holon;
      case 'location_Hor':
        return location_Hor;
      case 'location_Horeb_Sinai':
        return location_Horeb_Sinai;
      case 'location_Horesh':
        return location_Horesh;
      case 'location_Hor_haggidgad':
        return location_Hor_haggidgad;
      case 'location_Hula':
        return location_Hula;
      case 'location_Hyrcania':
        return location_Hyrcania;
      case 'location_Ibleam_Gath_rimmon':
        return location_Ibleam_Gath_rimmon;
      case 'location_Iconium':
        return location_Iconium;
      case 'location_Idumea':
        return location_Idumea;
      case 'location_Ijon':
        return location_Ijon;
      case 'location_Illyricum':
        return location_Illyricum;
      case 'location_India':
        return location_India;
      case 'location_Indus':
        return location_Indus;
      case 'location_Issachar':
        return location_Issachar;
      case 'location_Issus':
        return location_Issus;
      case 'location_Italy':
        return location_Italy;
      case 'location_Ituraea':
        return location_Ituraea;
      case 'location_Iye_abarim':
        return location_Iye_abarim;
      case 'location_Jabbok':
        return location_Jabbok;
      case 'location_Jabesh_gilead':
        return location_Jabesh_gilead;
      case 'location_Jabneel_Judah':
        return location_Jabneel_Judah;
      case 'location_Jabneel_Naphtali':
        return location_Jabneel_Naphtali;
      case 'location_Jacobs_Fountain':
        return location_Jacobs_Fountain;
      case 'location_Jagur':
        return location_Jagur;
      case 'location_Janoah':
        return location_Janoah;
      case 'location_Jarash_Gerasa':
        return location_Jarash_Gerasa;
      case 'location_Jarmuth_Judah':
        return location_Jarmuth_Judah;
      case 'location_Jarmuth_Ramoth_Issachar':
        return location_Jarmuth_Ramoth_Issachar;
      case 'location_Jattir':
        return location_Jattir;
      case 'location_Jebusites':
        return location_Jebusites;
      case 'location_Jehud':
        return location_Jehud;
      case 'location_Jericho':
        return location_Jericho;
      case 'location_Jerusalem':
        return location_Jerusalem;
      case 'location_Jeshanah':
        return location_Jeshanah;
      case 'location_Jeshua_Sheba':
        return location_Jeshua_Sheba;
      case 'location_Jezreel':
        return location_Jezreel;
      case 'location_Jogbehah':
        return location_Jogbehah;
      case 'location_Jokneam_Jokmeam':
        return location_Jokneam_Jokmeam;
      case 'location_Joppa':
        return location_Joppa;
      case 'location_Jordan':
        return location_Jordan;
      case 'location_Jotbah':
        return location_Jotbah;
      case 'location_Jotbathah':
        return location_Jotbathah;
      case 'location_Judah_tribe':
        return location_Judah_tribe;
      case 'location_Judah_Judea':
        return location_Judah_Judea;
      case 'location_Juttah':
        return location_Juttah;
      case 'location_Kabul':
        return location_Kabul;
      case 'location_Kadesh_Kadesh_barnea':
        return location_Kadesh_Kadesh_barnea;
      case 'location_Kain':
        return location_Kain;
      case 'location_Kanah':
        return location_Kanah;
      case 'location_Kedemoth':
        return location_Kedemoth;
      case 'location_Kedesh_Issachar':
        return location_Kedesh_Issachar;
      case 'location_Kedesh_Naphtali':
        return location_Kedesh_Naphtali;
      case 'location_Keilah':
        return location_Keilah;
      case 'location_Kenites':
        return location_Kenites;
      case 'location_Khorsabad':
        return location_Khorsabad;
      case 'location_Kibroth_hattaavah':
        return location_Kibroth_hattaavah;
      case 'location_Kidron':
        return location_Kidron;
      case 'location_Kings_Road':
        return location_Kings_Road;
      case 'location_Kir_of_Moab_Kir_hareseth':
        return location_Kir_of_Moab_Kir_hareseth;
      case 'location_Kiriathaim':
        return location_Kiriathaim;
      case 'location_Kiriath_arba_Hebron':
        return location_Kiriath_arba_Hebron;
      case 'location_Kiriath_jearim':
        return location_Kiriath_jearim;
      case 'location_Kishion_Kedesh_Issachar':
        return location_Kishion_Kedesh_Issachar;
      case 'location_Kishon':
        return location_Kishon;
      case 'location_Kittim_Cyprus':
        return location_Kittim_Cyprus;
      case 'location_Lachish':
        return location_Lachish;
      case 'location_Laish_Dan_city':
        return location_Laish_Dan_city;
      case 'location_Laodicea':
        return location_Laodicea;
      case 'location_Lassharon':
        return location_Lassharon;
      case 'location_Lebanon':
        return location_Lebanon;
      case 'location_Lebonah':
        return location_Lebonah;
      case 'location_Lehi':
        return location_Lehi;
      case 'location_Libnah':
        return location_Libnah;
      case 'location_Libya':
        return location_Libya;
      case 'location_Lod_Lydda':
        return location_Lod_Lydda;
      case 'location_Lo_debar_Debir':
        return location_Lo_debar_Debir;
      case 'location_Luz_Bethel':
        return location_Luz_Bethel;
      case 'location_Lycaonia':
        return location_Lycaonia;
      case 'location_Lycia':
        return location_Lycia;
      case 'location_Lydda_Lod':
        return location_Lydda_Lod;
      case 'location_Lydia':
        return location_Lydia;
      case 'location_Lystra':
        return location_Lystra;
      case 'location_Maacah':
        return location_Maacah;
      case 'location_Macedonia':
        return location_Macedonia;
      case 'location_Machpelah_See_also_Hebron':
        return location_Machpelah_See_also_Hebron;
      case 'location_Madmannah_Beth_marcaboth':
        return location_Madmannah_Beth_marcaboth;
      case 'location_Madon':
        return location_Madon;
      case 'location_Magadan':
        return location_Magadan;
      case 'location_Mahanaim':
        return location_Mahanaim;
      case 'location_Makaz':
        return location_Makaz;
      case 'location_Makkedah':
        return location_Makkedah;
      case 'location_Malta':
        return location_Malta;
      case 'location_Mamre':
        return location_Mamre;
      case 'location_Manahath':
        return location_Manahath;
      case 'location_Manasseh':
        return location_Manasseh;
      case 'location_Maon':
        return location_Maon;
      case 'location_Maracanda_Samarkand':
        return location_Maracanda_Samarkand;
      case 'location_Marah':
        return location_Marah;
      case 'location_Marathon':
        return location_Marathon;
      case 'location_Mareshah':
        return location_Mareshah;
      case 'location_Masada':
        return location_Masada;
      case 'location_Medeba':
        return location_Medeba;
      case 'location_Media':
        return location_Media;
      case 'location_Megiddo':
        return location_Megiddo;
      case 'location_Memphis_Noph':
        return location_Memphis_Noph;
      case 'location_Mephaath':
        return location_Mephaath;
      case 'location_Merom':
        return location_Merom;
      case 'location_Meroz':
        return location_Meroz;
      case 'location_Mesopotamia':
        return location_Mesopotamia;
      case 'location_Michmash':
        return location_Michmash;
      case 'location_Michmethath':
        return location_Michmethath;
      case 'location_Midian':
        return location_Midian;
      case 'location_Migdal_el':
        return location_Migdal_el;
      case 'location_Migdol':
        return location_Migdol;
      case 'location_Migron':
        return location_Migron;
      case 'location_Miletus':
        return location_Miletus;
      case 'location_Minni':
        return location_Minni;
      case 'location_Minnith':
        return location_Minnith;
      case 'location_Misrephoth_maim':
        return location_Misrephoth_maim;
      case 'location_Mitylene':
        return location_Mitylene;
      case 'location_Mizpah_Mizpeh_Benjamin':
        return location_Mizpah_Mizpeh_Benjamin;
      case 'location_Mizpah_Mizpeh_Gad':
        return location_Mizpah_Mizpeh_Gad;
      case 'location_Moab':
        return location_Moab;
      case 'location_Moreh':
        return location_Moreh;
      case 'location_Moresheth':
        return location_Moresheth;
      case 'location_Moriah':
        return location_Moriah;
      case 'location_Mozah':
        return location_Mozah;
      case 'location_Myra':
        return location_Myra;
      case 'location_Mysia':
        return location_Mysia;
      case 'location_Naarah':
        return location_Naarah;
      case 'location_Nain':
        return location_Nain;
      case 'location_Naphtali':
        return location_Naphtali;
      case 'location_Nazareth':
        return location_Nazareth;
      case 'location_Neapolis':
        return location_Neapolis;
      case 'location_Neballat':
        return location_Neballat;
      case 'location_Nebo_city':
        return location_Nebo_city;
      case 'location_Nebo_Pisgah':
        return location_Nebo_Pisgah;
      case 'location_Negeb':
        return location_Negeb;
      case 'location_Neiel':
        return location_Neiel;
      case 'location_Nephtoah':
        return location_Nephtoah;
      case 'location_Netophah':
        return location_Netophah;
      case 'location_Nibshan':
        return location_Nibshan;
      case 'location_Nile':
        return location_Nile;
      case 'location_Nineveh':
        return location_Nineveh;
      case 'location_Nisibis':
        return location_Nisibis;
      case 'location_No_amon_Thebes':
        return location_No_amon_Thebes;
      case 'location_Nob':
        return location_Nob;
      case 'location_Noph_Memphis':
        return location_Noph_Memphis;
      case 'location_Mount_of_Olives':
        return location_Mount_of_Olives;
      case 'location_On':
        return location_On;
      case 'location_Ono':
        return location_Ono;
      case 'location_Ophel':
        return location_Ophel;
      case 'location_Ophni':
        return location_Ophni;
      case 'location_Ophrah_in_Issachar':
        return location_Ophrah_in_Issachar;
      case 'location_Ophrah_Ephraim':
        return location_Ophrah_Ephraim;
      case 'location_Paddan_aram':
        return location_Paddan_aram;
      case 'location_Palmyra_Tadmor':
        return location_Palmyra_Tadmor;
      case 'location_Pamphylia':
        return location_Pamphylia;
      case 'location_Paphos':
        return location_Paphos;
      case 'location_Parah':
        return location_Parah;
      case 'location_Paran':
        return location_Paran;
      case 'location_Parthia':
        return location_Parthia;
      case 'location_Pasargadae':
        return location_Pasargadae;
      case 'location_Patara':
        return location_Patara;
      case 'location_Patmos':
        return location_Patmos;
      case 'location_Pella_Decapolis':
        return location_Pella_Decapolis;
      case 'location_Pella_Macedonia':
        return location_Pella_Macedonia;
      case 'location_Penuel':
        return location_Penuel;
      case 'location_Perea':
        return location_Perea;
      case 'location_Perga':
        return location_Perga;
      case 'location_Pergamum':
        return location_Pergamum;
      case 'location_Perizzites':
        return location_Perizzites;
      case 'location_Persepolis':
        return location_Persepolis;
      case 'location_Persia':
        return location_Persia;
      case 'location_Phasis':
        return location_Phasis;
      case 'location_Philadelphia_Asia_Minor':
        return location_Philadelphia_Asia_Minor;
      case 'location_Philadelphia_Rabbah':
        return location_Philadelphia_Rabbah;
      case 'location_Philippi':
        return location_Philippi;
      case 'location_Philistia':
        return location_Philistia;
      case 'location_Phoenicia':
        return location_Phoenicia;
      case 'location_Phrygia':
        return location_Phrygia;
      case 'location_Pihahiroth':
        return location_Pihahiroth;
      case 'location_Pirathon':
        return location_Pirathon;
      case 'location_Pisgah_Nebo':
        return location_Pisgah_Nebo;
      case 'location_Pisidia':
        return location_Pisidia;
      case 'location_Pontus':
        return location_Pontus;
      case 'location_Promised_Land':
        return location_Promised_Land;
      case 'location_Ptolemais':
        return location_Ptolemais;
      case 'location_Punon':
        return location_Punon;
      case 'location_Pura':
        return location_Pura;
      case 'location_Puteoli':
        return location_Puteoli;
      case 'location_Rabbah_Philadelphia':
        return location_Rabbah_Philadelphia;
      case 'location_Rakkath':
        return location_Rakkath;
      case 'location_Ramah_Benjamin':
        return location_Ramah_Benjamin;
      case 'location_Ramah_Naphtali':
        return location_Ramah_Naphtali;
      case 'location_Ramah_Arimathea_Ephraim':
        return location_Ramah_Arimathea_Ephraim;
      case 'location_Ramah_Baal_Baalath_beer_Simeon':
        return location_Ramah_Baal_Baalath_beer_Simeon;
      case 'location_Rameses':
        return location_Rameses;
      case 'location_Ramoth_Jarmuth':
        return location_Ramoth_Jarmuth;
      case 'location_Ramoth_gilead':
        return location_Ramoth_gilead;
      case 'location_Raphana':
        return location_Raphana;
      case 'location_Rehob':
        return location_Rehob;
      case 'location_Rehoboth':
        return location_Rehoboth;
      case 'location_Rephidim':
        return location_Rephidim;
      case 'location_Reuben':
        return location_Reuben;
      case 'location_Rhagae':
        return location_Rhagae;
      case 'location_Rhegium':
        return location_Rhegium;
      case 'location_Rhodes':
        return location_Rhodes;
      case 'location_Riblah':
        return location_Riblah;
      case 'location_Rimmon_Ain_Simeon':
        return location_Rimmon_Ain_Simeon;
      case 'location_Rimmon_perez':
        return location_Rimmon_perez;
      case 'location_Rissah':
        return location_Rissah;
      case 'location_Rogelim':
        return location_Rogelim;
      case 'location_Rome':
        return location_Rome;
      case 'location_Rumah':
        return location_Rumah;
      case 'location_Salamis_Cyprus':
        return location_Salamis_Cyprus;
      case 'location_Salamis_Greece':
        return location_Salamis_Greece;
      case 'location_Salem_Jerusalem':
        return location_Salem_Jerusalem;
      case 'location_Salim':
        return location_Salim;
      case 'location_City_of_Salt':
        return location_City_of_Salt;
      case 'location_Samaria':
        return location_Samaria;
      case 'location_Samaria_city':
        return location_Samaria_city;
      case 'location_Samarkand_Maracanda':
        return location_Samarkand_Maracanda;
      case 'location_Samos':
        return location_Samos;
      case 'location_Samothrace':
        return location_Samothrace;
      case 'location_Sansannah_Hazar_susah':
        return location_Sansannah_Hazar_susah;
      case 'location_Sardis':
        return location_Sardis;
      case 'location_Sarid':
        return location_Sarid;
      case 'location_Scythia':
        return location_Scythia;
      case 'location_Scythopolis_Beth_shean':
        return location_Scythopolis_Beth_shean;
      case 'location_Secacah':
        return location_Secacah;
      case 'location_Seir':
        return location_Seir;
      case 'location_Seir_Judah':
        return location_Seir_Judah;
      case 'location_Seleucia':
        return location_Seleucia;
      case 'location_Sepphoris':
        return location_Sepphoris;
      case 'location_Shaalbim':
        return location_Shaalbim;
      case 'location_Shaaraim_Sharuhen':
        return location_Shaaraim_Sharuhen;
      case 'location_Shamir_Samaria_city':
        return location_Shamir_Samaria_city;
      case 'location_Shaphir':
        return location_Shaphir;
      case 'location_Sharon':
        return location_Sharon;
      case 'location_Sharuhen':
        return location_Sharuhen;
      case 'location_Sheba_kingdom':
        return location_Sheba_kingdom;
      case 'location_Sheba_Jeshua':
        return location_Sheba_Jeshua;
      case 'location_Shechem':
        return location_Shechem;
      case 'location_Shephelah':
        return location_Shephelah;
      case 'location_Shilhim_Sharuhen':
        return location_Shilhim_Sharuhen;
      case 'location_Shiloh':
        return location_Shiloh;
      case 'location_Shimron':
        return location_Shimron;
      case 'location_Shittim':
        return location_Shittim;
      case 'location_Shunem':
        return location_Shunem;
      case 'location_Shur':
        return location_Shur;
      case 'location_Shushan':
        return location_Shushan;
      case 'location_Sicily':
        return location_Sicily;
      case 'location_Sidon':
        return location_Sidon;
      case 'location_Siloam':
        return location_Siloam;
      case 'location_Sin':
        return location_Sin;
      case 'location_Sinai_Horeb':
        return location_Sinai_Horeb;
      case 'location_Siwa__Oasis_of':
        return location_Siwa__Oasis_of;
      case 'location_Smyrna':
        return location_Smyrna;
      case 'location_Socoh_Judah':
        return location_Socoh_Judah;
      case 'location_Socoh_Manasseh':
        return location_Socoh_Manasseh;
      case 'location_Sodom':
        return location_Sodom;
      case 'location_Sogdiana':
        return location_Sogdiana;
      case 'location_Sorek':
        return location_Sorek;
      case 'location_Spain_Tarshish':
        return location_Spain_Tarshish;
      case 'location_Succoth_Egypt':
        return location_Succoth_Egypt;
      case 'location_Succoth_Gad':
        return location_Succoth_Gad;
      case 'location_Susa_Shushan':
        return location_Susa_Shushan;
      case 'location_Sychar':
        return location_Sychar;
      case 'location_Syene':
        return location_Syene;
      case 'location_Syracuse':
        return location_Syracuse;
      case 'location_Syria':
        return location_Syria;
      case 'location_Taanach':
        return location_Taanach;
      case 'location_Taanath_shiloh':
        return location_Taanath_shiloh;
      case 'location_Tabor':
        return location_Tabor;
      case 'location_Tadmor_Palmyra':
        return location_Tadmor_Palmyra;
      case 'location_Tahpanhes':
        return location_Tahpanhes;
      case 'location_Tamar':
        return location_Tamar;
      case 'location_Tappuah':
        return location_Tappuah;
      case 'location_Tarshish_Spain':
        return location_Tarshish_Spain;
      case 'location_Tarsus':
        return location_Tarsus;
      case 'location_Taxila':
        return location_Taxila;
      case 'location_Tekoa':
        return location_Tekoa;
      case 'location_Tema':
        return location_Tema;
      case 'location_Thebes_No_amon':
        return location_Thebes_No_amon;
      case 'location_Thebez':
        return location_Thebez;
      case 'location_Thessalonica':
        return location_Thessalonica;
      case 'location_Thrace':
        return location_Thrace;
      case 'location_Thyatira':
        return location_Thyatira;
      case 'location_Tiberias':
        return location_Tiberias;
      case 'location_Tigris':
        return location_Tigris;
      case 'location_Timnah_Judah':
        return location_Timnah_Judah;
      case 'location_Timnah_Judah_Dan':
        return location_Timnah_Judah_Dan;
      case 'location_Timnath_serah':
        return location_Timnath_serah;
      case 'location_Tiphsah':
        return location_Tiphsah;
      case 'location_Tirzah':
        return location_Tirzah;
      case 'location_Tochen_Ether':
        return location_Tochen_Ether;
      case 'location_Trachonitis':
        return location_Trachonitis;
      case 'location_Troas':
        return location_Troas;
      case 'location_Troy':
        return location_Troy;
      case 'location_Tyre':
        return location_Tyre;
      case 'location_Tyropoeon_Valley':
        return location_Tyropoeon_Valley;
      case 'location_Ur':
        return location_Ur;
      case 'location_Via_Maris':
        return location_Via_Maris;
      case 'location_Yarkon':
        return location_Yarkon;
      case 'location_Yarmuk':
        return location_Yarmuk;
      case 'location_Yiron':
        return location_Yiron;
      case 'location_Zagros':
        return location_Zagros;
      case 'location_Zalmonah':
        return location_Zalmonah;
      case 'location_Zanoah':
        return location_Zanoah;
      case 'location_Zaphon':
        return location_Zaphon;
      case 'location_Zarephath':
        return location_Zarephath;
      case 'location_Zarethan':
        return location_Zarethan;
      case 'location_Zebulun':
        return location_Zebulun;
      case 'location_Zered':
        return location_Zered;
      case 'location_Zeredah':
        return location_Zeredah;
      case 'location_Zereth_shahar':
        return location_Zereth_shahar;
      case 'location_Ziklag':
        return location_Ziklag;
      case 'location_Zin':
        return location_Zin;
      case 'location_Zion':
        return location_Zion;
      case 'location_Ziph':
        return location_Ziph;
      case 'location_Zoan':
        return location_Zoan;
      case 'location_Zorah':
        return location_Zorah;
      default:
        return null;
    }
  }
}
