name: CD

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  deploy-web:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: ./scripts/gen_i10n.sh
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NWT_READING }}
          channelId: live

  deploy-windows:
    name: Deploy to Microsoft Store
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: cmd /c scripts\win_gen_i10n.bat
      - run: flutter config --enable-windows-desktop
      - uses: microsoft/setup-msstore-cli@v1

      - name: Configure the Microsoft Store CLI
        run: >
          msstore reconfigure
          --tenantId ${{ secrets.MICROSOFT_PARTNER_CENTER_ENTRA_TENANT_ID }}
          --clientId ${{ secrets.MICROSOFT_PARTNER_CENTER_CLIENT_ID }}
          --clientSecret ${{ secrets.MICROSOFT_PARTNER_CENTER_CLIENT_SECRET }}
          --sellerId ${{ secrets.MICROSOFT_PARTNER_CENTER_SELLER_ID }}

      - name: Create MSIX package
        run: msstore package .

      - name: Publish MSIX to the Microsoft Store
        run: msstore publish -v
